default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'topup_api_user') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'topup#123') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 5432

development:
  primary:
    <<: *default
    database: benefit_platform_development
    migrations_paths: db/migrate
  queue:
    <<: *default
    database: benefit_platform_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: benefit_platform_test

production:
  primary: &primary_production
    <<: *default
    database: benefit_platform_production
  cache:
    <<: *primary_production
    database: benefit_platform_mock_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: benefit_platform_mock_production_queue
    migrations_paths: db/queue_migrate
